### ISSUE TITLE
About dimension independent programming

### ISSUE THREAD

**Issue by Jack12xl** [taichi-dev/taichi_three#29]
About dimension independent programming:

Sry this issue is more like a search-for-help.

##### Basically, I am gonna extend a 2d simulation to 3d(or more specifically, this [repo](https://github.com/Jack12xl/a-toy-fluid-engine)).  

Although here [mpm3d](https://github.com/taichi-dev/taichi/blob/master/examples/mpm3d.py) already shows a good example on both supporting 2d and 3d, I still wonder is there any more elegant way to do this in my setting?

 For example, to calculate divergence in 2d setting, we could say:

```python
 @ti.kernel
    def calDivergence(self, vf: ti.template(), vd: ti.template()):
        # vf : Data wrapper class for velocity field 
        # vf as ti.Vector.field(2, dtype=ti.f32, shape=[512, 512])
        # vd : Data wrapper class for velocity divergence
        # vd as ti.field(dtype=ti.f32, shape=[512, 512])
        for I in ti.grouped(vf.field):
            vl = vf.sample(I + ts.D.zy).x
            vr = vf.sample(I + ts.D.xy).x
            vb = vf.sample(I + ts.D.yz).y
            vt = vf.sample(I + ts.D.yx).y
            vc = vf.sample(I)
            # omit the boundary condition
            vd[I] = (vr - vl + vt - vb) * 0.5
           
```

For clarification( in case it matters ):

`calDivergence` is defined in [here](https://github.com/Jack12xl/a-toy-fluid-engine/blob/de42c775421b5f99ae48c60de7edeee028dec104/Grid/collocatedGridData.py#L99)

`vf class` is defined [here](https://github.com/Jack12xl/a-toy-fluid-engine/blob/master/Grid/DataGrid.py)

#### To 3D

Here I want to extend this `calDivergence` to 3D: `vf` and `vd` would become 3d,

which means :

`vf` would more or less become `ti.Vector.field(3, dtype=ti.f32, shape=[512, 512, 512])`

and 

`vd` : `ti.field(dtype=ti.f32, shape=[512, 512, 512])`

So our `calDivergence` would become something like

```python
            
    @ti.kernel
    def calDivergence(self, vf: ti.template(), vd: ti.template()):
        if ( dimension2 ):
            for I in ti.grouped(vf.field):
                vl = vf.sample(I + ts.D.zy).x
                vr = vf.sample(I + ts.D.xy).x
                vb = vf.sample(I + ts.D.yz).y
                vt = vf.sample(I + ts.D.yx).y
                vc = vf.sample(I)
                # omit boundary condition 
                vd[I] = (vr - vl + vt - vb) * 0.5
        elif ( dimension3 ):
            for I in ti.grouped(vf.field):
                vl = vf.sample(I + ts.D.zyy).x
                vr = vf.sample(I + ts.D.xyy).x
                vb = vf.sample(I + ts.D.yzy).y
                vt = vf.sample(I + ts.D.yxy).y
                vh = vf.sample(I + ts.D.yyz).z
                vq = vf.sample(I + ts.D.yyx).z
                vc = vf.sample(I)
                # omit boundary condition
                vd[I] = (vr - vl + vt - vb + vq - vh) * 0.5
```

But in this way, the function would become somewhat clunky, hard to maintain and extend.

I mean, `ti.grouped` is already make it kind of dimension-independent. So I wonder is there any trick(magic function) to make it more dimension-independent ?  

For example:

```python
@ti.kernel
    def calDivergence(self, vf: ti.template(), vd: ti.template()):
        for I in ti.grouped(vf.field):
            tmp = magic_function(vf, vd, dim)
            # tmp = [vl, vr, vb, vt] in dimension 2
            # tmp = [vl, vr, vb, vt, vh, vq] in dimension 3
            
            vd[I] = sum(tmp)
```

**Comment by archibate** [comment]
import taichi as ti 
 
@ti.kernel 
def calDivergence(self, vf: ti.template(), vd: ti.template()): 
 &nbsp;&nbsp;&nbsp;for I in ti.grouped(vf.field): 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret = 0.0 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for i in ti.static(range(dim)): 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D = ti.Vector.unit(dim, i) 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;res += vf.sample(I + D)[i] 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret -= vf.sample(I - D)[i] 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;vd[I] = ret * 0.5 
 
@ti.func 
def magic_function(vf, vd): 
 &nbsp;&nbsp;&nbsp;ret = ti.static([]) 
 &nbsp;&nbsp;&nbsp;for i in ti.static(range(dim)): 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;D = ti.Vector.unit(dim, i) 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret.append(vf.sample(I + D)[i]) 
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ret.append(vf.sample(I - D)[i]) 
 &nbsp;&nbsp;&nbsp;return ret
&nbsp;


双笙子佯谬
1931127624@qq.com

上海拆桥学院
桥梁爆破小组首席执行官


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年11月10日(星期二) 晚上6:12
收件人: "taichi-dev/taichi_three"<taichi_three@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [taichi-dev/taichi_three] About dimension independent programming (#29)





 
Sry this issue is more like a search-for-help.
 
Basically, I am gonna extend a 2d simulation to 3d(or more specifically, this repo).
 
Although here mpm3d already shows a good example on both supporting 2d and 3d, I still wonder is there any more elegant way to do this in my setting?
 
For example, to calculate divergence in 2d setting, we could say:
  @ti.kernel     def calDivergence(self, vf: ti.template(), vd: ti.template()):         # vf : Data wrapper class for velocity field          # vf as ti.Vector.field(2, dtype=ti.f32, shape=[512, 512])         # vd : Data wrapper class for velocity divergence         # vd as ti.field(dtype=ti.f32, shape=[512, 512])         for I in ti.grouped(vf.field):             vl = vf.sample(I + ts.D.zy).x             vr = vf.sample(I + ts.D.xy).x             vb = vf.sample(I + ts.D.yz).y             vt = vf.sample(I + ts.D.yx).y             vc = vf.sample(I)             # omit the boundary condition             vd[I] = (vr - vl + vt - vb) * 0.5            
 
For clarification( in case it matters ):
 
calDivergence is defined in here
 
vf class is defined here
 
To 3D
 
Here I want to extend this calDivergence to 3D: vf and vd would become 3d,
 
which means :
 
vf would more or less become ti.Vector.field(3, dtype=ti.f32, shape=[512, 512, 512])
 
and
 
vd : ti.field(dtype=ti.f32, shape=[512, 512, 512])
 
So our calDivergence would become something like
                  @ti.kernel     def calDivergence(self, vf: ti.template(), vd: ti.template()):         if ( dimension2 ):             for I in ti.grouped(vf.field):                 vl = vf.sample(I + ts.D.zy).x                 vr = vf.sample(I + ts.D.xy).x                 vb = vf.sample(I + ts.D.yz).y                 vt = vf.sample(I + ts.D.yx).y                 vc = vf.sample(I)                 # omit boundary condition                  vd[I] = (vr - vl + vt - vb) * 0.5         elif ( dimension3 ):             for I in ti.grouped(vf.field):                 vl = vf.sample(I + ts.D.zyy).x                 vr = vf.sample(I + ts.D.xyy).x                 vb = vf.sample(I + ts.D.yzy).y                 vt = vf.sample(I + ts.D.yxy).y                 vh = vf.sample(I + ts.D.yyz).z                 vq = vf.sample(I + ts.D.yyx).z                 vc = vf.sample(I)                 # omit boundary condition                 vd[I] = (vr - vl + vt - vb + vq - vh) * 0.5
 
I mean, ti.grouped is already make it kind of dimension-independent. So I wonder is there any trick to make it more dimension-independent ?
 
For example:
 @ti.kernel     def t_div(self, vf: ti.template(), vd: ti.template()):         for I in ti.grouped(vf.field):             tmp = magic_function(vf, vd, dim)             # tmp = [vl, vr, vb, vt] in dimension 2             # tmp = [vl, vr, vb, vt, vh, vq] in dimension 3                          vd[I] = sum(tmp)

**Comment by Jack12xl** [comment]
Oh yeah♂ That's good ♂

That ti.Vector.unit really does the trick. Thanks a lot !

I'm closing it now.
