### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'smart'

### ISSUE THREAD

**Issue by zhaoyueyi** [taichi-dev/taichi_three#43]
你好！
    请问在`TriangleRaster`类的`render_occup()`方法中出现的用法：
`for f in ti.smart(self.get_faces_range()):`
中的`ti.smart()`是定义在哪里的？
    我在使用的时候报了标题所示的错误
    或者是有什么可替代的写法
    感谢！

**Comment by archibate** [comment]
see taichi_three/tina/hacker.py
ti.smart is actually the same as ti.static, except it can transform 'continue' to taichi op instead of python op.









无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Tue, Apr 27, 2021 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [taichi-dev/taichi_three] AttributeError: module 'taichi' has no attribute 'smart' (#43)




 
你好！
 请问在TriangleRaster类的render_occup()方法中出现的用法：
 for f in ti.smart(self.get_faces_range()):
 中的ti.smart()是定义在哪里的？
 我在使用的时候报了标题所示的错误
 或者是有什么可替代的写法
 感谢！

**Comment by zhaoyueyi** [comment]
Thanks for your reply! It helps me a lot
Hope you have a wonderful day :-D
